service: magicbatches-${self:provider.stage}

package:
  individually: true

provider:
  name: aws
  runtime: python3.9
  profile: ${opt:profile, "geoff"}
  region: ${opt:region, "us-west-2"}
  stage: ${opt:stage, "dev"}

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
    layer:
      name: magicbatches-layer-${self:provider.stage}
      description: Magic Batches layer ${self:provider.stage}
      compatibleRuntimes:
        - python3.9

functions:
  app:
    package:
      include:
        - "main.py"
      exclude:
        - "requirements.txt"
        - "package.json"
        - "package-lock.json"
        - ".serverless/**"
        - ".virtualenv/**"
        - "node_modules/**"
        - ".github/**"

    handler: app/main.handler
    environment:
      STAGE: ${self:provider.stage}
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          method: any
          path: /{proxy+}